### ISSUE TITLE
How can I find the CWE type for each function in .jsonl?

### ISSUE THREAD

**Issue by youpengl** [vinci-grape/VulEmpirical#1]
Dear authors,

Thanks for the wonderful empirical study. I am wondering how can I find the CWE type for each function in jsonl? I tried to use the key "index" number to find the CWE type in the original BigVul.csv but it seems to be unmatched. Could you give me some instructions? Thank you! 

Best,
Leopold

**Comment by youpengl** [comment]
@vinci-grape

**Comment by vinci-grape** [comment]
Hello, we have uploaded the original data file.

**Comment by youpengl** [comment]
Thanks a lot :)

**Comment by youpengl** [comment]
Sorry for the confusion. I do not find the updated file.

Best,
Youpeng
________________________________
